tiltak-notifikasjon:
  altinn-tilgangstyring:
    arbeidstrening: nav_tiltak_arbeidstrening
    midlertidigLonnstilskudd: nav_tiltak_midlertidig-lonnstilskudd
    varigLonnstilskudd: nav_tiltak_varig-lonnstilskudd
    sommerjobb: nav_tiltak_sommerjobb
    mentor: nav_tiltak_mentor
    inkluderingstilskudd: nav_tiltak_inkluderingstilskudd
    vtao: nav_tiltak_varig-tilrettelagt-arbeid-ordinaer
    firearigLonnstilskudd: nav_tiltak_firearig-lonnstilskudd-for-unge
  pdl-api:
    uri: https://pdl-api.prod-fss-pub.nais.io/graphql
    scope: api://prod-fss.pdl.pdl-api/.default

  produsent-api:
    url: http://notifikasjon-produsent-api.fager/api/graphql
no.nav.security.jwt:
  client:
    registration:
      notifikasjoner:
        token-endpoint-url: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: api://prod-gcp.fager.notifikasjon-produsent-api/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      pdl-api:
        token-endpoint-url: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: ${tiltak-notifikasjon.pdl-api.scope}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
