tiltak-notifikasjon:
  altinn-tilgangstyring:
    arbtreningServiceCode: 5332
    arbtreningServiceEdition: 1
    ltsMidlertidigServiceCode: 5516
    ltsMidlertidigServiceEdition: 1
    ltsVarigServiceCode: 5516
    ltsVarigServiceEdition: 2
    sommerjobbServiceCode: 5516
    sommerjobbServiceEdition: 3
    mentorServiceCode: 5516
    mentorServiceEdition: 4
    inkluderingstilskuddServiceCode: 5516
    inkluderingstilskuddServiceEdition: 5
    vtaoServiceCode: 5516
    vtaoServiceEdition: 6
  pdl-api:
    uri: https://pdl-api.dev-fss-pub.nais.io/graphql
    scope: api://dev-fss.pdl.pdl-api/.default

  produsent-api:
    url: http://notifikasjon-produsent-api.fager/api/graphql
no.nav.security.jwt:
  azure-access-token:
    discoveryurl: "https://login.microsoftonline.com/62366534-1ec3-4962-8869-9b5535279d0b/.well-known/openid-configuration"
    accepted_audience: "https://management.core.windows.net/"
  client:
    registration:
      notifikasjoner:
        token-endpoint-url: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: api://dev-gcp.fager.notifikasjon-produsent-api/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      pdl-api:
        token-endpoint-url: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: ${tiltak-notifikasjon.pdl-api.scope}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic

logging:
  level:
    no.nav.team_tiltak.felles.persondata: DEBUG
