tiltak-notifikasjon:
  altinn-tilgangstyring:
    sommerjobbServiceCode: 5516
    sommerjobbServiceEdition: 3
    ltsMidlertidigServiceCode: 5516
    ltsMidlertidigServiceEdition: 1
    ltsVarigServiceCode: 5516
    ltsVarigServiceEdition: 2
    arbtreningServiceCode: 5332
    arbtreningServiceEdition: 2
    mentorServiceCode: 5516
    mentorServiceEdition: 4
    inkluderingstilskuddServiceCode: 5516
    inkluderingstilskuddServiceEdition: 5
