apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: tiltak-notifikasjon-alert
  namespace: team-tiltak
  labels:
    team: team-tiltak
spec:
  groups:
    - name: tiltak-notifikasjon-alert
      rules:
        - alert: InstanceDown
          expr: count(up) == 0
          for: 3m
          annotations:
            consequence: Application is unavailable
            action: "Sjekk logs.adeo.no for logger: https://logs.adeo.no/s/nav-logs-legacy/app/r/s/llSjm"
            summary: |-
              tiltak-notifikasjon har ingen podder tilgjengelig
          labels:
            namespace: team-tiltak # required
            severity: critical
        - alert: TILTAK-NOTIFIKASJON ERROR!
          expr: sum(increase(logback_events_total{app="tiltak-notifikasjon",level="error"}[10m])) > 0
          for: 10s
          annotations:
            consequence: Feil i loggen til tiltak-notifikasjon
            action: "Sjekk logs.adeo.no for logger: https://logs.adeo.no/s/nav-logs-legacy/app/r/s/llSjm"
            summary: |-
              tiltak-notifikasjon har logget en feil :mild-panic-intensifies: Sjekk loggene om noe bør gjøres!
          labels:
            namespace: team-tiltak # required
            severity: critical
