apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "tiltak-notifikasjon"
  namespace: "team-tiltak"
  labels:
    "team": "team-tiltak"
spec:
  kafka:
    pool: nav-prod
  image: {{image}}
  port: 8080
  liveness:
    path: /internal/actuator/health/liveness
    initialDelay: 30
    timeout: 1
    periodSeconds: 30
    failureThreshold: 10
  readiness:
    path: /internal/actuator/health/readiness
    initialDelay: 30
    timeout: 1
    periodSeconds: 30
    failureThreshold: 10
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: "2000Mi"
    requests:
      cpu: "200m"
      memory: "1000Mi"
  env:
    - name: MILJO
      value: prod-gcp
  envFrom:
    - secret: tiltak-notifikasjon-unleash-api-token
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        tier: db-custom-1-3840
        name: tiltak-notifikasjon
        flags:
          - name: cloudsql.logical_decoding # flagget som må settes for bigquery greier
            value: "on" # flagget som må settes
        databases:
          - name: tiltak-notifikasjon
            users:
              - name: datastream
            envVarPrefix: DB
        diskAutoresize: true # Datastream bruker en del lagringsplass
  azure:
    application:
      enabled: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: team_logs
        - id: loki
  accessPolicy:
    outbound:
      rules:
        - application: "notifikasjon-produsent-api"
          namespace: "fager"
      external:
        - host: team-tiltak-unleash-api.nav.cloud.nais.io
        - host: pdl-api.prod-fss-pub.nais.io
  prometheus:
    enabled: true
    path: /internal/actuator/prometheus
