apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "tiltak-notifikasjon"
  namespace: "team-tiltak"
  labels:
    "team": "team-tiltak"
spec:
  kafka:
    pool: nav-dev
  image: {{image}}
  liveness:
    path: /internal/health
    initialDelay: 20
    timeout: 60
  readiness:
    path: /internal/health
    initialDelay: 20
    timeout: 60
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: "200m"
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "512Mi"
