apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: tiltak-notifikasjon
  namespace: team-tiltak
  labels:
    team: team-tiltak
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: team-tiltak
  secretName: tiltak-notifikasjon-unleash-api-token
  environment: {{ unleash-environment }}