### Test hent mine notifikasjoner
# Kun til testing i dev - er ikke deployet i prod
GET http://localhost:8080/internal/admin/hent-mine-saker
Content-Type: application/json

{
  "avtaleId": "f193e2dd-a01e-4b48-94e1-3e94ad6cb8b5",
  "merkelapp": "Lønnstilskudd"
}

### f193e2dd-a01e-4b48-94e1-3e94ad6cb8b5 - mange notifikasjoner
### 64d627f1-f69a-4613-a20e-056fe0778947