### Test hent mine notifikasjoner
# Kun til testing i dev - er ikke deployet i prod
GET http://localhost:8080/internal/admin/hent-mine-saker
Content-Type: application/json

{
  "avtaleId": "5b0f7322-2e3e-4fa8-bfbc-1badac292c61",
  "merkelapp": "Lønnstilskudd"
}