name: Bygg og deploy master

on:
  push:
    branches:
      - 'main'

env:
  GITHUB_REPOSITORY: ${{ github.repository }}
  IMAGE: ghcr.io/${{ github.repository }}/tiltak-notifikasjon:${{ github.sha }}

jobs:
  bygg:
    name: Bygg
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v3

      - name: Oppsett Java 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'
      - name: Bygg og test med Maven
        run: mvn package -B -Dsurefire.useFile=false
      - name: Bygg, tag og push Docker-image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${GITHUB_TOKEN} | docker login ghcr.io -u ${GITHUB_REPOSITORY} --password-stdin
          docker build --tag ${IMAGE} .
          docker push ${IMAGE}

  deploy-dev:
    name: Deploy til dev
    runs-on: ubuntu-latest
    needs: bygg
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v3

      - name: Deploy til dev-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/nais-dev.yml,nais/alerts.yml,nais/unleash-apitoken.yml
          PRINT_PAYLOAD: true
          VAR: unleash-environment=development

  deploy-prod:
    name: Deploy til prod
    runs-on: ubuntu-latest
    needs: bygg
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v3

      - name: Deploy til prod-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais/nais-prod.yml,nais/alerts.yml,nais/unleash-apitoken.yml
          PRINT_PAYLOAD: true
          VAR: unleash-environment=production